### PR TITLE
Notification Token did not work

### PR DESCRIPTION
**Pull request by moofish32**
In order to make this trigger occur I had to use the ATLAS_TOKEN var. I actually could not prove the notification token var is actually set. Am I missing something?

### CODE REVIEW

**Comment by clstokes** [comment]
`ATLAS_TOKEN_NOTIFICATION` would have to be set separately in the build configuration in Atlas. The intent for separating them was to manage the authorization scopes separately. Make sense @moofish32?

**Comment by moofish32** [comment]
@clstokes - makes sense. I have looked at Atlas documentation, but can't figure out how to set this up?

**Comment by clstokes** [comment]
The `ATLAS_TOKEN_NOTIFICATION` variable itself or some other part?

For the `ATLAS_TOKEN_NOTIFICATION`, you would create a token for your own Atlas user or an Atlas service account and then add it as an environment variable.

image

I'm happy to hop on a call if needed. You know how to find me. :)

**Comment by moofish32** [comment]
@clstokes -- got it. Closing this. I expected Atlas to do it for me based on that name.

**Comment by clstokes** [comment]
Ah... got it. Yea only `ATLAS_TOKEN` is set automatically.

**Pull request closed without merging**
